library(rchess)

setwd("C:/Users/kelvy/OneDrive/KelvynsFiles/Masters Program/Stat Comp/ChessProject")
games <- read.csv("games.csv", header = T)
games$moves[4]
v <- strsplit(games$moves, split = " ")
v
v[[1]]
v[[1]][13] == "O-O"

chss <- Chess$new()
paste0("chss",
       "$move(", m, ")")
s <- eval(parse(text = "2+3"))
e4 <- "e4"
s <- eval(parse(text = paste0("chss", "$move(", "e4", ")")))
s



#detach("package:rchess", unload = T)
#rchess::chessboardjs()
#data("chesswc")
#library(dplyr)
#count(chesswc, event)
#data("chessopenings")
#head(chessopenings)
chss <- Chess$new()
class(chss)
plot(chss)
chss$move("e4")#$move("e5")
plot(chss)
chss$move("e5")
plot(chss)
chss
chss$history()
chss$move("Nf3")
plot(chss)
chss$move("Nf6")
plot(chss)
chss
chss$move("Bc4")
plot(chss)
chss$move("Bc5")
plot(chss)
chss$move("O-O")
plot(chss)
chss$move("0-0")
chss$move("O-O")
plot(chss)
chss$move("Nxe5")
plot(chss)
chss$move("Nxe4")
plot(chss)
s <- chss$history_detail()
chss$square_color("a1")
chss$move("a4")
plot(chss)
chss$move("h5")
plot(chss)
chss$move("a5")
plot(chss)
chss$move("h4")
plot(chss)
chss$move("g4")
plot(chss)
chss$move("hxg3")
plot(chss)
chss$move("hxg3")
plot(chss)
chss$move("Nxg3")
plot(chss)
chss$move("Re1")
plot(chss)
chss$move("Qh4")
plot(chss)
chss$move("Bxf7")
chss$move("Bxf7+")
plot(chss)
chss$move("Rxf7")
plot(chss)
chss$move("Nxf7")
plot(chss)
chss$move("Qh1++")
chss$move("Qh1#")
plot(chss)
chss$in_checkmate()
chss

chss$square_color("a1")
chss$get("e4")
chss$get("h1")
chss$history()
s <- chss$history_detail()
